// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_yTzCP4Nx3uwlnWP13nsZKtzTlJ22dZs',
    appId: '1:783970946186:web:f226cdffa8fcb387867173',
    messagingSenderId: '783970946186',
    projectId: 'chat-6a336',
    authDomain: 'chat-6a336.firebaseapp.com',
    storageBucket: 'chat-6a336.appspot.com',
    measurementId: 'G-5X1W2N43WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0kTo-arTZUP71dFOaLQTezhD3aH5e4_U',
    appId: '1:783970946186:android:4aefbb0ba6713bfa867173',
    messagingSenderId: '783970946186',
    projectId: 'chat-6a336',
    storageBucket: 'chat-6a336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA8_JGVZEbUMsDE76WUda8eyv4Tn0n7oM',
    appId: '1:783970946186:ios:ac1965df06108262867173',
    messagingSenderId: '783970946186',
    projectId: 'chat-6a336',
    storageBucket: 'chat-6a336.appspot.com',
    iosClientId: '783970946186-vsgi38pn0lpb2lacq95frd75735gsk3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA8_JGVZEbUMsDE76WUda8eyv4Tn0n7oM',
    appId: '1:783970946186:ios:ac1965df06108262867173',
    messagingSenderId: '783970946186',
    projectId: 'chat-6a336',
    storageBucket: 'chat-6a336.appspot.com',
    iosClientId: '783970946186-vsgi38pn0lpb2lacq95frd75735gsk3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );
}
